Models/Autore.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Biblioteca_EntityFramework.Models
{
    [Table("autori")]
    public class Autore
    {
        [Key]
        public long AutoreId { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public ICollection<Libro>? Libri { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Biblioteca_EntityFramework.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Libro.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Biblioteca_EntityFramework.Models
{
    public enum Stato
    {
        Disponibile,
        InPrestito
    }

    [Table("libri")]
    public class Libro
    {
        [Key]
        public long ID { get; set; }
        public string Titolo { get; set; }
        public DateTime Data { get; set; }

        public Stato stato { get; set; }
        public string ISBN { get; set; }

        public ICollection<Autore>? Autori { get; set; }

        public ICollection<Prestito>? Prestiti { get; set; }
    }
}

Models/Prestito.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Biblioteca_EntityFramework.Models
{
    [Table("prestiti")]
    public class Prestito
    {
        [Key]
        public long IdPrestito { get; set; }

        public DateTime data { get; set; }
    }
}

Models/Utente.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Biblioteca_EntityFramework.Models
{
    [Table("utenti")]
    public class Utente
    {
        [Key]
        public long UtenteID { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string? Email { get; set; }

        public ICollection<Prestito>? Prestiti { get; set; }
    }
}

Controllers/HomeController.cs
using Biblioteca_EntityFramework.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Biblioteca_EntityFramework.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LibroesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Biblioteca_EntityFramework;
using Biblioteca_EntityFramework.Models;

namespace Biblioteca_EntityFramework.Controllers
{
    public class LibroesController : Controller
    {
        private readonly LibraryContext _context;

        public LibroesController(LibraryContext context)
        {
            _context = context;
        }

        // GET: Libroes
        public async Task<IActionResult> Index()
        {
              return _context.Libri != null ? 
                          View(await _context.Libri.ToListAsync()) :
                          Problem("Entity set 'LibraryContext.Libri'  is null.");
        }

        // GET: Libroes/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Libri == null)
            {
                return NotFound();
            }

            var libro = await _context.Libri.Where(l => l.ID == id)
                .Include(l => l.Autori)
                .FirstOrDefaultAsync();

            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // GET: Libroes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Libroes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(/*[Bind("ID,Titolo,Data,stato,ISBN,numeroDiPagine,authorsNames,authorsLastNames")]*/ Libro libro)
        {
            for(int i = 0; i < 5; i++)
            {
                if(Request.Form.ContainsKey("authorsNames-" + i) && Request.Form.ContainsKey("authorsLastNames-" + i))
                {
                    Microsoft.Extensions.Primitives.StringValues nome;
                    Microsoft.Extensions.Primitives.StringValues cognome;
                    Request.Form.TryGetValue("authorsNames-" + i, out nome);
                    Request.Form.TryGetValue("authorsLastNames-" + i, out cognome);
                    Autore autore = new Autore() { Nome=nome, Cognome=cognome };
                    _context.Add(autore);
                    if(libro.Autori == null)
                    {
                        libro.Autori = new List<Autore>();
                    }
                    libro.Autori.Add(autore);
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(libro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libroes/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Libri == null)
            {
                return NotFound();
            }

            var libro = await _context.Libri.FindAsync(id);
            if (libro == null)
            {
                return NotFound();
            }
            return View(libro);
        }

        // POST: Libroes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("ID,Titolo,Data,stato,ISBN,numeroDiPagine")] Libro libro)
        {
            if (id != libro.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(libro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LibroExists(libro.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(libro);
        }

        // GET: Libroes/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Libri == null)
            {
                return NotFound();
            }

            var libro = await _context.Libri
                .FirstOrDefaultAsync(m => m.ID == id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        // POST: Libroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Libri == null)
            {
                return Problem("Entity set 'LibraryContext.Libri'  is null.");
            }
            var libro = await _context.Libri.FindAsync(id);
            if (libro != null)
            {
                _context.Libri.Remove(libro);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LibroExists(long id)
        {
          return (_context.Libri?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Libroes/Create.cshtml
@model Biblioteca_EntityFramework.Models.Libro

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titolo" class="control-label"></label>
                <input asp-for="Titolo" class="form-control" />
                <span asp-validation-for="Titolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="stato" class="control-label"></label>
                <select asp-for="stato" class="form-control">
                    <option value=@Stato.Disponibile>Disponibile</option>
                    <option value=@Stato.InPrestito>In Prestito</option>
                </select>
                <span asp-validation-for="stato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            





            <button id="addAutore">Aggiungi Autore</button>
            <div class="form-group" id="autoriGroup"></div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        let i = 0;
        const autoriGroup = document.getElementById("autoriGroup");
        document.getElementById("addAutore").addEventListener("click",
            () =>{
                event.preventDefault();

                const inputNameLabel = document.createElement("label");
                inputNameLabel.innerText = "Nome"
                const inputName = document.createElement("input");
                inputName.name = "authorsNames-" + i;
                inputName.type = "text";
                inputName.classList = "mb-3 form-control";

                const inputLastNameLabel = document.createElement("label");
                inputLastNameLabel.innerText = "Cognome"
                const inputLastName = document.createElement("input");
                inputLastName.name = "authorsLastNames-" + i;
                inputLastName.type = "text";
                inputLastName.classList = "mb-3 form-control";

                i++;

                autoriGroup.appendChild(inputNameLabel);
                autoriGroup.appendChild(inputName);

                autoriGroup.appendChild(inputLastNameLabel);
                autoriGroup.appendChild(inputLastName);
            }
        );
    </script>
}

Views/Libroes/Delete.cshtml
@model Biblioteca_EntityFramework.Models.Libro

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.stato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.stato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Libroes/Details.cshtml
@model Biblioteca_EntityFramework.Models.Libro

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titolo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.stato)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.stato)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        
        <dt class = "col-sm-2">
            Autori
        </dt>
        <dd class = "col-sm-10">
            <ul>@foreach (var item in Model.Autori)
                {
                    <li>
                        @Html.DisplayFor(modelItem => item.Nome) @Html.DisplayFor(modelItem => item.Cognome)
                    </li>
                }
            </ul>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Libroes/Edit.cshtml
@model Biblioteca_EntityFramework.Models.Libro

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Libro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Titolo" class="control-label"></label>
                <input asp-for="Titolo" class="form-control" />
                <span asp-validation-for="Titolo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Data" class="control-label"></label>
                <input asp-for="Data" class="form-control" />
                <span asp-validation-for="Data" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="stato" class="control-label"></label>
                <select asp-for="stato" class="form-control">
                    <option value=@Stato.Disponibile>Disponibile</option>
                    <option value=@Stato.InPrestito>In Prestito</option>
                </select>
                <span asp-validation-for="stato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ISBN" class="control-label"></label>
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Libroes/Index.cshtml
@model IEnumerable<Biblioteca_EntityFramework.Models.Libro>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titolo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Data)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.stato)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ISBN)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titolo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stato)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca_EntityFramework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Biblioteca_EntityFramework.styles.css" asp-append-version="true" />
</head>
<body>
<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca MVC Entity Framework</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libroes" asp-action="Index">Libri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Utenti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Prestiti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Biblioteca_EntityFramework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>